### PR TITLE
Bump version to v.3.5.3

### PR DESCRIPTION
**Pull request by glennj**

### CODE REVIEW

**Comment by glennj** [comment]
@ErikSchierboom I see in bin/release.sh that I'll be pushing a tag to main -- do I have permission to do that?

**Comment by ErikSchierboom** [comment]
> I'll be pushing a tag to main -- do I have permission to do that?

I'm not sure. Maybe we just try it?

**Comment by glennj** [comment]
Need to have this merged first.

**Comment by QuLogic** [comment]
Did this version not get tagged? I only see 3.5.2 and 3.5.4 now. Not a big deal though.

**Comment by ErikSchierboom** [comment]
Yes, I think there was an issue @glennj ?

**Comment by glennj** [comment]
I got hung up on the PGP keys, then just kind of lost track of the task.

**Pull request merged**
