### PR TITLE
Display post-submission call to action message from submission API response

### PR DESCRIPTION
**Pull request by nilbus**
(was: Revamp the call to review action)

This is part of our gamification experiment (https://github.com/exercism/discussions/issues/123) and effort to increase review participation (https://github.com/exercism/discussions/issues/88).

*Update*: This wording will be provided by exercism.io API in the submission response. Both the wording and the timing will be controlled with feature flags in the same manner as the rest of the experiment.

I originally proposed this in https://github.com/exercism/discussions/issues/88:

> Now that you've completed this exercise, let's see how your solution compares to others: _[url]_
> To benefit the most from this exercise, find 3 or more submissions that you can
> learn something from, have questions about, or have suggestions for.
> Post your thoughts and questions in the comments, and start a discussion.
> Revise your solution to incorporate what you learned.

I'm instead now proposing this:

> Your _[language]_ solution for _[problem]_ has been submitted.
> 
> Programmers generally spend far more time reading code than writing it.
> To benefit the most from this exercise, find 3 or more submissions that you can
> learn something from, have questions about, or have suggestions for.
> Post your thoughts and questions in the comments, and start a discussion.
> Consider revising your solution to incorporate what you learn.
> 
> Yours and others' solutions to this problem:
> _[url]_

Goal: Set up elements of a [skill atom][]: goals, actions, challenge, motivation

- It maintains flow by describing reviewing code as the natural next step. I removed the link to your own submission, because it's going to be at the top of the list anyway, and I want to suggest one clear path forward.
- It reminds you that your motivation is to learn and helps fulfill that motivation. I.e. informational and not controlling.
- It suggests goals and actions aligned with that motivation, appropriate for people at all levels: learn, ask, incorporate, suggest.
- It challenges you to find at least 3 interesting submissions and to participate.
- _I removed the competition bit, in favor of [the exercism way][]._

[skill atom]: https://github.com/exercism/discussions/issues/123#user-content-skill-atoms
[the exercism way]: https://github.com/exercism/exercism.io/blob/master/docs/the-exercism-way.md

### CODE REVIEW

**Comment by nilbus** [comment]
I removed the link to your own submission, because it's going to be at the top of the list anyway, and I want to suggest one clear path forward.

**Comment by nilbus** [comment]
In order to match experimental/control grouping with exercism.io, I'm going to have to get the github username. Right now, that's a field on `submission`, but it's not set. I'll investigate this further tomorrow, but if anyone has thoughts on that, please let me know.

**Comment by nilbus** [comment]
It appears that the `Username` field was only ever used by the Download feature. Prior to that, there was a `GithubUsername` field that Katrina removed, but that was input by the user, not part of the submission response, which would be more reliable.

**Comment by kytrinyx** [comment]
> I'm going to have to get the github username.

@nilbus Where do you need to get the GitHub username?

This is the call to action that the CLI outputs to the terminal, right?

If so, I think that we should consider having the textual response defined in the API, not hard-coded in the CLI, so that this can more easily be controlled by the feature flags. The CLI can easily display text that it receives as part of the API response.

As mentioned earlier, we will need to get people to update the command-line client to enable the feature. We could add a banner to the site for the experimental week that asks people to do so.

**Comment by kytrinyx** [comment]
> This is the call to action that the CLI outputs to the terminal, right?

Duh. Sorry, my brain is just waking up. Of course it is.

> I think that we should consider having the textual response defined in the API

I do think this is a better approach.

In order to do that we would need to change the response in https://github.com/exercism/exercism.io/blob/master/api/v1/routes/iterations.rb#L43

And change the CLI to read from that field for the output.

Then the CLI won't have to implement `runExperiment`.

**Comment by nilbus** [comment]
> I'm going to have to get the github username.

I originally planned to get the username to reproduce the algorithm that determined whether the experiment was on or off, but I much prefer your idea of supplying the message from the server. I was going in the same direction, already planning to use feature flags to either supply the github username or not and change the message based on that, but it's way better being able to update the messaging via API response anytime we want.

I'll make sure this change is forward and backward compatible between exercism.io and cli versions.

> We could add a banner to the site for the experimental week that asks people to do so.

Brilliant, I'm glad you thought of this.

**Comment by nilbus** [comment]
This change forward/backward compatible, tested in all combinations of new & old exercism.io and new & old cli. This is paired with exercism/exercisim.io#3414 but does not need not need a synchronized release.

Before, with old exercism.io, old cli, or new exercism.io with the `cli-call-to-action` feature flag off:

```
$ exercism s hamming/hamming.rb
Your Ruby solution for Hamming has been submitted. View it here:
http://localhost:4567/submissions/8a68fb9f28124a9999bb699c7f3bd230

See related solutions and get involved here:
http://localhost:4567/tracks/ruby/exercises/hamming
```

After, with new exercism.io, new cli, and the `cli-call-to-action` feature flag on:

```
$ exercism s hamming/hamming.rb
Your ruby solution for hamming has been submitted.

Programmers generally spend far more time reading code than writing it.
To benefit the most from this exercise, find 3 or more submissions that you can
learn something from, have questions about, or have suggestions for.
Post your thoughts and questions in the comments, and start a discussion.
Consider revising your solution to incorporate what you learn.

Yours and others' solutions to this problem:
http://localhost:4567/tracks/ruby/exercises/hamming
```

This is ready to go, if it looks good to you.

**Pull request merged**
