### PR TITLE
[nextercism] skip empty files on submit

### PR DESCRIPTION
**Pull request by aldraco**
Work in progress, still haven't been able to test it out. Looking to address #472.

While trying to test, I'm running into issues trying to fetch exercises with my built `testercism` binary. When I run `./testercism download hello-world` I get an empty Error. I then tried running `./testercism prepare -t python` which looked to have a string escape error, which may be happening for other commands too given they all use the same structure, though I didn't see a similar string format error for it:

https://github.com/exercism/cli/blob/nextercism/config/api_config.go#L13-L16

(`troubleshoot` does not seem to indicate any connectivity problems.)

Error for `prepare` command:

```
Error: parse https://api.exercism.io/v1/tracks/%!!(string=python)s(MISSING): invalid URL escape "%!!"
```

Are these known errors? 

Thanks! I'll take another look this weekend when I'm not so tired. :smile:

### CODE REVIEW

**Comment by kytrinyx** [comment]
Oh, shoot. My guess is that this is a problem in the library, not with you! 💙 

I'm running on empty myself, but my plan for today is to catch up on all the CLI-related issues and PRs so I'll see if I can test this out and provide any pointers or suggestions.

**Comment by kytrinyx** [comment]
Ok! I had an almost-nap, and now I'm back to feeling quite human again.

It was most certainly my fault. I've submitted a fix for it here: #495

You'll also need to call `./testercism configure --token=YOUR-TOKEN`, and you can find your token on the https://v2.exercism.io/my/settings page.

I'm pretty sure that the empty error is because we haven't done any proper error handling for stuff like that yet (... note to self!).

✨ thanks, good luck etc etc and holler if you get stuck!

**Comment by aldraco** [comment]
Aha, @kytrinyx thank you! I was also trying to use my old token from v1, so thanks for pointing that out as well.

**Comment by aldraco** [comment]
Thanks again for your help! Removed the [wip] tag and is ready for a review.

**Pull request closed without merging**
