### PR TITLE
Open browser from cli

### PR DESCRIPTION
**Pull request by zabawaba99**
This should address #83 . It's still missing some tests for the new API that I'd like to add.

I'd also like to add unit tests for the new command that was added but I'm not quiet sure how to go about that. Any suggestions?

### CODE REVIEW

**Comment by Tonkpils** [comment]
Works well on OSX. @kytrinyx know anyone that could test this on Windows and Linux?

**Comment by kytrinyx** [comment]
/cc @jwood803, @LegalizeAdulthood  want to give this a shot on windows?

I don't know anyone off the top of my head who uses exercism with linux, I'd be willing to hope that it works and then deal with bugfixes later.

**Comment by jwood803** [comment]
Sure, I can try this out this week or so.

**Comment by zabawaba99** [comment]
@jwood803 Were you able to validate this functionality on Windows?

**Comment by kytrinyx** [comment]
If not, that's fine. We can release a bugfix if it turns out that there's a problem. I'll give this until tomorrow and then merge.

**Comment by kytrinyx** [comment]
Merging. I'll put out a release in a moment.

**Pull request merged**
