### PR TITLE
Add GoReportCard badge to README

### PR DESCRIPTION
**Pull request by gliptak**
GoReportCard displays a number of Go "health" metrics and links back into the Github source allowing quick corrections.
The project's report can be reviewed at https://goreportcard.com/report/github.com/exercism/cli

### CODE REVIEW

**Comment by gliptak** [comment]
please /review @kytrinyx

**Comment by kytrinyx** [comment]
Would you please update your pull request body to describe why you think this is a useful change?

**Comment by gliptak** [comment]
@kytrinyx added a short explanation above

**Comment by kytrinyx** [comment]
@gliptak I hadn't ever looked at GoReportCard, but this looks really nice. Thanks for suggesting this!

**Pull request merged**
