### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-)

### CODE REVIEW

**Comment by nywilken** [comment]
@katrinleinweber thanks for making this fix. Any chance you would be up for addressing #666 in this PR?

**Comment by katrinleinweber** [comment]
Only crudely, I'm afraid. I can remove all commands that are no longer present in [the `/cmd` folder](https://github.com/exercism/cli/tree/master/cmd), but learning the ropes of this [cobra](https://github.com/spf13/cobra) thingy is currently too much, sorry.

**Comment by katrinleinweber** [comment]
Like this? My 1st encounter with bash-completion-underlying code 😕

**Comment by nywilken** [comment]
@katrinleinweber sorry for now mentioning you can ignore the bash completion in Cobra. Thanks for updating the command list. 

I’m glong to merge this and then use it to update the bash version and a few of the options.

**Pull request merged**
