### PR TITLE
Protect existing solutions from being overwritten by 'download'

### PR DESCRIPTION
**Pull request by haguro**
Add an optional `--force` flag to the download command to overwrite an existing exercise directory as suggested in [several issues and discussions](https://github.com/exercism/exercism/issues/5432#issuecomment-739580317).

Should fix exercism/exercism#5432 and probably #872 too.

Feedback or further guidance is much appreciated 👍

### CODE REVIEW

**Comment by haguro** [comment]
The travis builds for Go 1.11 and 1.12 are failing due to compile errors in the `testify` package. Building with Go latest (and locally Go 1.15) is successful. Is there a reason for the cli still needs to be built with those old versions?

**Comment by iHiD** [comment]
@haguro Thanks :) I don't speak Go so this will require @ekingery taking a look :)

**Review by ekingery — APPROVED** [review]
Code and tests look great, thanks so much, @haguro!  If you are interested in additional contributions to the exercism, we have plenty of work to do on the Go track to get ready for the V3 launch. Let me know if so!

**Comment by haguro** [comment]
Many thanks @ekingery. Yes, I would be happy to lend a hand!

**Comment by ekingery** [comment]
> Many thanks @ekingery. Yes, I would be happy to lend a hand!

Excellent! If you would like a slack invite, send me your email address (mine is my username at gmail). If you don't like Slack, I'll just add you to an issue or two once the work is ready to be distributed.

**Pull request merged**
