### PR TITLE
Removing team functionality

### LINKED ISSUE #956: Remove teams for v3
The CLI currently has functionality in it for submitting to teams. With the launch of v3 that won't need to be in the CLI any more as the submitting to teams is a separate step in the website. So that code can be removed. It's not critical it happens quickly, but the API won't support the teams option any more, so probably best to launch the new CLI with the website launch.

### PR DESCRIPTION
**Pull request by ekingery**
Resolves #956

### CODE REVIEW

**Comment by ekingery** [comment]
Hi everyone. The CI build failed on the previous versions of Go ("1.11.x", "1.12.x"). It passed on 1.15. We can update the Travis config to only build for more recent versions of Go. Another option would be to upgrade the go modules and see if that resolves the issue for older versions. This might be a good idea regardless. I'm open to other options, what does everyone think?

**Comment by NobbZ** [comment]
Given the presence of `go.mod` and `go.sum` I assume that this is already a module.

**Comment by ekingery** [comment]
> Given the presence of `go.mod` and `go.sum` I assume that this is already a module.

That's right. I meant upgrade the modules themselves. The build error, on first glance, seems to be due to a deprecated language feature in an old version of stretchr/testify, but I'm just guessing. I figured upgrading the modules might be worthwhile, and could potentially resolve the old build errors. That said, I don't know of a good reason to keep the CLI building on old Go versions, as this doesn't impact distribution or compatibility (to my knowledge).

**Comment by iHiD** [comment]
@ekingery Awesome! Thanks 😀 

 I've converted this to a Draft PR to reflect that it shouldn't be merged until we launch v3 🙂 I don't speak Go so I'll have to rely on @kytrinyx for that bit when she's back from her tech-break!

**Comment by ekingery** [comment]
> > Given the presence of `go.mod` and `go.sum` I assume that this is already a module.
> 
> That's right. I meant upgrade the modules themselves. The build error, on first glance, seems to be due to a deprecated language feature in an old version of stretchr/testify, but I'm just guessing. I figured upgrading the modules might be worthwhile, and could potentially resolve the old build errors. That said, I don't know of a good reason to keep the CLI building on old Go versions, as this doesn't impact distribution or compatibility (to my knowledge).

I removed the old Go versions from the Travis build and they passed, as expected. I went ahead and upgraded the dependent modules as well.

**Comment by ErikSchierboom** [comment]
@ekingery Hi! We're quite a way into developing Exercism v3 and with that, the `config.json` files structure will also be changed a bit. We would like `configlet` to also be able to handle v3 config files. Would you perhaps be interested in adding this functionality to `configlet`?

**Comment by ekingery** [comment]
> @ekingery Hi! We're quite a way into developing Exercism v3 and with that, the `config.json` files structure will also be changed a bit. We would like `configlet` to also be able to handle v3 config files. Would you perhaps be interested in adding this functionality to `configlet`?

I am interested, for sure. I can't make any guarantees that I'll be able to do it in a timely manner, but I'd be glad to give it a shot.

**Comment by ErikSchierboom** [comment]
@ekingery Brilliant! I think you're on our Slack channel, right? If so, please contact me on Slack (@ErikSchierboom). If not, let me know and I'll send you an invite link :)

**Comment by haguro** [comment]
@ekingery May we perhaps move 7241ff5ae4eaac6df0c3e272f64f6a5275420dd3 and 7d89733684505e9aea26c39bb9cc44788b132537 to a seperate PR? Don't believe they need to wait for v3 and it would fix travis build results on all PRs submitted until then.

**Comment by ekingery** [comment]
> @ekingery May we perhaps move [7241ff5](https://github.com/exercism/cli/commit/7241ff5ae4eaac6df0c3e272f64f6a5275420dd3) and [7d89733](https://github.com/exercism/cli/commit/7d89733684505e9aea26c39bb9cc44788b132537) to a seperate PR? Don't believe they need to wait for v3 and it would fix travis build results on all PRs submitted until then.

I think we should be fine now, as [01cb5bc0df991af80ad871d06dad6a4ea6148cc8] fixed the travis.yml issues. I'd be happy to upgrade the go modules, although that could be integrated into whatever PR is next - unless I'm missing something and the builds are still failing after `main` is merged in?

**Comment by haguro** [comment]
> I think we should be fine now, as [[01cb5bc](https://github.com/exercism/cli/commit/01cb5bc0df991af80ad871d06dad6a4ea6148cc8)] fixed the travis.yml issues. I'd be happy to upgrade the go modules, although that could be integrated into whatever PR is next - unless I'm missing something and the builds are still failing after `main` is merged in?
Nope I think that should be all good for now. I had just missed that that PR had been merged yesterday :)

**Pull request closed without merging**
