### PR TITLE
refactored exercism.io to exercism.org

### PR DESCRIPTION
**Pull request by ladokp**
Changed exercism.io to exercism.org after reading this conversation:
https://discord.com/channels/854117591135027261/1294074767682310164

### CODE REVIEW

**Review by iHiD — APPROVED** [review]
I'm good with this. Let's let someone else release the CLI this time. We can work out what permissions need to be given etc, and Erik can handhold them if needed rather than doing it himself.

**Comment by iHiD** [comment]
@glennj Would you like to take a stab at releasing this? (If so, we can open a forum thread for it where Erik can transfer any missing knowledge!)

**Comment by glennj** [comment]
Sure

**Comment by iHiD** [comment]
Great. Thanks! 

So the instructions are [here](https://github.com/exercism/cli/blob/main/RELEASE.md), but I guess you need keys/access. @ErikSchierboom Do you know what I need to give Glenn to make this happen? Thanks :)

**Comment by ErikSchierboom** [comment]
I do. Glenn needs a public key and password. I'll send it to him via the forum

**Comment by ladokp** [comment]
Will this be merged during the release? I'm just curious. 😄

**Comment by glennj** [comment]
Sorry for the delay everyone. I'll merge this then work on the release.

**Pull request merged**
