### PR TITLE
added --api option to exercism configure; updated tests

### PR DESCRIPTION
**Pull request by morphatic**
In response to #145

Summary of changes:

* add `--api` and `-a` parameters to `exercism configure`
* updated `config_test.go` to test success of changes

### CODE REVIEW

**Comment by morphatic** [comment]
Per conversation in #146 I also added a couple more steps in the Development section of the README file to clarify the process for contributing developers.

**Comment by kytrinyx** [comment]
This is great! Thanks so much for jumping in and getting this done so quickly. I'll get cut a new release tonight or tomorrow morning.

**Comment by kytrinyx** [comment]
I've published a new release, but only here on github (I've not updated the homebrew repository, I sometimes skip patch releases there). Let me know if it would be easier on your students if there's a homebrew installation option.

**Comment by morphatic** [comment]
Thank you!  My class starts on Monday and I'll have 52 brand new recruits, the majority of whom have never written any code at all.  I don't think many of them will be savvy enough to realize how cool the homebrew option is.  It will be good for them to follow the instructions for manual installation. :)

**Comment by kytrinyx** [comment]
> It will be good for them to follow the instructions for manual installation. :)

No doubt :) There's so much implicit knowledge in getting something like that working. I really had no idea until I tried to explain it to beginners.

**Pull request merged**
