### PR TITLE
Explain how to run the tests locally

### PR DESCRIPTION
**Pull request by jbranchaud**
I'm not sure if I got the wording quite right, but I think it's useful to note (in the `README`) how to run the tests locally.

I got this from the `.travis.yml` file. Perhaps there is a different, preferred way of running the tests for this project?

### CODE REVIEW

**Comment by lcowell** [comment]
Thanks! This definitely works and is the only way I'd know to do ti too. It feels a little onerous. Using a tool like `gb` would allow us to simply say `gb test`. Anyone else know a simpler way to call the tests?

**Comment by Tonkpils** [comment]
@jbranchaud @lcowell `go test ./...` works just fine for me. It doesn't seem like `vendor` folder includes any test files maybe `godep` handles this when vendoring?

**Comment by Tonkpils** [comment]
Yeah, it seems you have to explicitly vendor with a `-t` flag when saving deps if you want to include test files with Godep so the instructions should just be `go test ./...` https://github.com/tools/godep#how-to-use-godep-with-a-new-project

**Comment by Tonkpils** [comment]
Closed by https://github.com/exercism/cli/commit/4edbbc88f48c4dfd872060febc94d6d6c3a110b9

**Pull request closed without merging**
