### PR TITLE
Make Download Error Message Start At a New Line

### PR DESCRIPTION
**Pull request by shmulik-klein**
A fix for #513 issue

### CODE REVIEW

**Comment by nywilken** [comment]
@shmulik-klein thanks for the PR. I took a quick look at why your PR was failing and found that your fork is out of sync with upstream.

Please fetch and pull upstream to update your fork and rebase your `newline-after-download-error` branch off of nextercism. We have some documentation on updating remotes and rebasing at https://github.com/exercism/docs/blob/master/contributing/git-basics.md#rebasing

After you rebase, you should change the target branch for your PR from nextercism-alpha to just nextercism. Feel free to give a holler if you need help or run into any issues.

**Comment by shmulik-klein** [comment]
@nywilken Thanks for your fast feedback! I'm might be missing something but issue #513 refers to the following `nextercism` version and error message:
```
~ $ nextercism version
exercism version 3.0.0-alpha.3
~ $ nextercism download
need an exercise name or a solution --uuid~ $
``` 
and I can only see those literals on the `nextercism-alpha` branch, am I still need to make `nextercism` the target branch ?

**Comment by kytrinyx** [comment]
@shmulik-klein those literals are the ones in the previous release. The `nextercism` branch is where we will make the next release from, so that is the one that you should branch off of. ⚡️

**Comment by shmulik-klein** [comment]
@kytrinyx , but this issue doesn't occur on `nextercism`, is it means that this one can be closed ?

**Comment by kytrinyx** [comment]
Ooooh! Yes, in that case let's close both this one and the other one. So sorry about that, and thank you for helping clear it up!

**Pull request closed without merging**
